dist: xenial

language: generic

cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

addons:
  apt:
    packages:
      - libgmp-dev

matrix:
  include:
  - env: STK=lts-13.6
  - env: STK=lts-12.26
  - env: STK=lts-11.22

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --resolver "$STK" --install-ghc test --only-dependencies

script:
- stack --no-terminal --resolver "$STK" test --haddock --no-haddock-deps
